// Date: 17/12/2012 8:53:48 a.m.
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package tutorial.generic;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTorchHolder extends ModelBase {
	// fields
	ModelRenderer Base;
	ModelRenderer Centre;
	ModelRenderer Edge1;
	ModelRenderer Edge2;
	ModelRenderer Edge3;
	ModelRenderer Edge4;
	ModelRenderer TorchHead;
	
	public ModelTorchHolder() {
		textureWidth = 64;
		textureHeight = 64;
		
		Base = new ModelRenderer(this, 16, 0);
		Base.addBox(-1F, 0F, -1F, 2, 5, 2);
		Base.setRotationPoint(0F, 19F, 0F);
		Base.setTextureSize(64, 64);
		Base.mirror = true;
		setRotation(Base, 0F, 0F, 0F);
		
		Centre = new ModelRenderer(this, 0, 0);
		Centre.addBox(-2F, 0F, -2F, 4, 2, 4);
		Centre.setRotationPoint(0F, 17F, 0F);
		Centre.setTextureSize(64, 64);
		Centre.mirror = true;
		setRotation(Centre, 0F, 0F, 0F);
		
		Edge1 = new ModelRenderer(this, 0, 6);
		Edge1.addBox(0F, 0F, 0F, 1, 4, 1);
		Edge1.setRotationPoint(-2F, 13F, 1F);
		Edge1.setTextureSize(64, 64);
		Edge1.mirror = true;
		setRotation(Edge1, 0F, 0F, 0F);
		
		Edge2 = new ModelRenderer(this, 4, 6);
		Edge2.addBox(0F, 0F, 0F, 1, 4, 1);
		Edge2.setRotationPoint(1F, 13F, 1F);
		Edge2.setTextureSize(64, 64);
		Edge2.mirror = true;
		setRotation(Edge2, 0F, 0F, 0F);
		
		Edge3 = new ModelRenderer(this, 8, 6);
		Edge3.addBox(0F, 0F, 0F, 1, 4, 1);
		Edge3.setRotationPoint(-2F, 13F, -2F);
		Edge3.setTextureSize(64, 64);
		Edge3.mirror = true;
		setRotation(Edge3, 0F, 0F, 0F);
		
		Edge4 = new ModelRenderer(this, 12, 6);
		Edge4.addBox(0F, 0F, 0F, 1, 4, 1);
		Edge4.setRotationPoint(1F, 13F, -2F);
		Edge4.setTextureSize(64, 64);
		Edge4.mirror = true;
		setRotation(Edge4, 0F, 0F, 0F);
		
		TorchHead = new ModelRenderer(this, 16, 7);
		TorchHead.addBox(-1F, 0F, -1F, 2, 4, 2);
		TorchHead.setRotationPoint(0F, 14F, 0F);
		TorchHead.setTextureSize(64, 64);
		TorchHead.mirror = true;
		setRotation(TorchHead, 0F, 0F, 0F);
	}
	
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5);
		Base.render(f5);
		Centre.render(f5);
		Edge1.render(f5);
		Edge2.render(f5);
		Edge3.render(f5);
		Edge4.render(f5);
		TorchHead.render(f5);
	}
	
	//Add this method to your Techne file and don't change anything else.
	public void renderModel(float f1) {
		Base.render(f1);
		Centre.render(f1);
		Edge1.render(f1);
		Edge2.render(f1);
		Edge3.render(f1);
		Edge4.render(f1);
		TorchHead.render(f1);
	}
	
	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
	}
	
}
